### PR TITLE
Add extra params for trigger

### PR DESCRIPTION
**Pull request by jdenquin**
Add extra params on triggers to permit custom select item component.

### CODE REVIEW

**Comment by jdenquin** [comment]
thanks for approve @cibernox, test fails but seems not linked with changes, could you merge it? :p

**Comment by cibernox** [comment]
@jdenquin I know they are not related, but I think I just fixed the errors. Can you rebase over master? I'm going to use your PR to verify the fix.

**Comment by jdenquin** [comment]
its done!

**Comment by cibernox** [comment]
Ok, all tests passed but 2.10, and I think I know why. Merging!

**Pull request merged**
