### PR TITLE
Proxy object detection

### PR DESCRIPTION
**Pull request by jlami**
Test and possible fix for #1147

### CODE REVIEW

**Comment by cibernox** [comment]
@runspired Summoning you so you can assess this fix.

**Comment by runspired** [comment]
@cibernox thinking it over

**Comment by cibernox** [comment]
I restarted the failed job.

**Comment by runspired** [comment]
My thoughts:

- I'm not sure this is generic enough although it should work for `ember-data` for now. There are other ways of constructing promise proxies than `ObjectProxy`, `ArrayProxy` and `PromiseProxyMixin`. I'm aware of many libraries that write their own simpler implementations, and I plan to write a simpler implementation for use in `ember-data` soon as well.

- This works towards solving the case where you encounter a PromiseProxy, but it seems likely there are still issues with generic proxies, which are even more likely to be stable than promise proxies

- I think the safest thing to do for PromiseProxies is to unwrap them. Unfortunately, the easiest way to do this is to observe a desired key (via observer or computed chain), which would be the best way to deal with generic proxies and other stable objects as well, but the level of abstraction here looks to prevent that at this time. That said, you could take an approach like the following to enable fixing `PromiseProxies` generically in the same manner as above in this PR.

```
function isPromiseProxy(potentialPromise) {
  if (typeof potentialPromise !== 'object' || potentialPromise === null || !potentialPromise.then) {
    return false;
  }

  // it is rare for a promiseProxy to not have one of `content` or `promise`
  // `unknownProperty` is the getter method that `Ember` looks for that allows an object to proxy
  if (potentialPromise.content || potentialPromise.promise || potentialPromise.unknownProperty) {
    return true;
  }

  return false;
}
```

Lastly, I'm working towards [eliminating](https://github.com/runspired/ember-data-experiments-mega-unstable) `PromiseProxy` and `PromiseArrayProxy` as a pattern used by `ember-data`, so there will come a happy future in which addon code does not be aware of these things so often. That said, the stable proxy and stable wrapper problem is very similar to the stable array problem, for which this library installs observers. It's likely that a little bit of refactoring would enable watching for changes in a more long-term vision manner.

**Comment by cibernox** [comment]
In that case I think we can merge this. The test alone it's worth it, and if ember-data simplifies object proxies that should make things easier.

It might not work for other promise-proxy implementations, but this should cover most of the codebases and other people can resolve promises before passing them to EPS.

**Pull request merged**
