### PR TITLE
Adding getDropdownItems test helper to ease testing

### PR DESCRIPTION
**Pull request by prasad457**
**summary:**

- Adding new test helper `getDropdownItems`.
- `getDropdownItems` will return all the displayed items in the `power-select` dropdown
- Using this test helper to assert the displayed drop down items.

### CODE REVIEW

**Comment by cibernox** [comment]
@prasad457 that is actually handy! Can you just add couple lines of comments in the code with that the method does and how to use it?

**Comment by cibernox** [comment]
I need to chase the failures in CI myself, I'm pretty sure they are not related to your changes.

**Comment by prasad457** [comment]
> @prasad457 that is actually handy! Can you just add couple lines of comments in the code with that the method does and how to use it?

@cibernox Thank you for the review, I've added the comments to the newly added method.
Let me know If I need to add in any other place like docs.

**Review by cibernox — APPROVED** [review]

**Comment by cibernox** [comment]
Thanks! I'll cut a new version with this soon

**Pull request merged**
