### PR TITLE
fix disabled options on touch devices

### PR DESCRIPTION
**Pull request by swoga**
This PR fixes a problem which allows to select disabled options on touch devices.

### CODE REVIEW

**Comment by cibernox** [comment]
Good catch! Can you add a test for this?

**Comment by swoga** [comment]
I have added a test for disabled options.
I needed to remove isTouchDevice, because when testing on desktop it is always set to false and I found no trivial way to overwrite it for testing.
I don't see any downside adding the event, even when there is no touch support.
The touch control tests also were only successful, because tap() fires onclick, but it didn't test the logic behind the touch events.

**Comment by cibernox** [comment]
@swoga you shouldn't have to remove that, you can run chrome with a specific flag to make it think it's on a touch device. Tests in CI run with that flag on:
https://github.com/cibernox/ember-power-select/blob/master/testem.js#L11

**Comment by swoga** [comment]
Thanks for the hint! I didn't know this parameter and simply ran the tests inside the browser.
Using `ember test` runs the tests as expected.
I have reverted the commit.

**Comment by cibernox** [comment]
Great, I'll merge and release a new version as soon as travis is green!

**Comment by cibernox** [comment]
@swoga thank you for the PR. I've release 2.3.2 with this fix 🎉

**Pull request merged**
