### PR TITLE
Update dependencies for more babel@6 testing.

### PR DESCRIPTION
**Pull request by rwjblue**
PR against babel@6 branch, to see how CI fairs with the updated deps.

`ember test` now passes though, so we are heading in the right direction...

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks like the same jobs are failing here as on master (haven't dug into what is causing master to fail though).

**Comment by cibernox** [comment]
Seems unrelated to me too. I'll merge it and check what is the cause (if it's not spurious) in the other branch.

**Comment by cibernox** [comment]
@rwjblue The error seems to be a regression introduced in 2.11.3. More info here: https://github.com/emberjs/ember.js/pull/14898

**Comment by cibernox** [comment]
In the meanwhile I'm going to comment that test.

**Pull request merged**
