### PR TITLE
Convert to array when it's possible

### PR DESCRIPTION
**Pull request by GCorbel**
This fix issue #380 

With ember data, it's not possible to do `items.get('0')` to have the first value and it have to be converted to array. 

I can't do an integration test because [this line](https://github.com/cibernox/ember-power-select/blob/master/tests/integration/components/power-select/ember-data-test.js#L20) gives an error because `server` is undefined.

### CODE REVIEW

**Comment by cibernox** [comment]
@GCorbel I've updated mirage and fixed the test suite so you can properly test this.

I think however that instead of `toArray` you should use objectAt
```js
if (!selected.objectAt) {
  selected = Ember.A(selected);
}
this.get('select.actions.choose')(selected.objectAt(e.target.dataset.selectedIndex));
```

**Comment by cibernox** [comment]
@GCorbel Do you have a moment for rebasing and amend this PR?

Thanks

**Comment by GCorbel** [comment]
Yep. I will do it right now!

**Comment by GCorbel** [comment]
I rebased it but I'm not able to reproduce the issue on tests.

    $('.ember-power-select-multiple-remove-btn')[0].click();

Do not work.

I will check to night.

**Comment by cibernox** [comment]
@GCorbel that is totally expected. This addon uses native events, not jquery events. Check how other tests do the same (`nativeMouseDown`)

**Comment by GCorbel** [comment]
I did my work! Thanks for your help!

**Comment by GCorbel** [comment]
Tests are failing. I'll fix it tomorrow.

**Comment by GCorbel** [comment]
Now it works.

**Comment by cibernox** [comment]
Thanks! I'll release a new beta very soon.

**Pull request merged**
