### PR TITLE
pass horizontalPosition through power-select-multiple

### PR DESCRIPTION
**Pull request by Pasikonik**
I forgot about multiple component

### CODE REVIEW

**Comment by cibernox** [comment]
I'm merging this now, but can you add a another test using the multiple component in another PR?

**Comment by cibernox** [comment]
Thanks!

**Comment by Pasikonik** [comment]
Sorry for slow response
Unfortunately I have problem with writing this test. When I want to test it, multiple component doesn't have even `ember-basic-dropdown--left` but it has `ember-basic-dropdown--transitioned-in` (in test). I checked this on sample and works perfectly. I don't know where could be difference. Can you help me?

**Comment by cibernox** [comment]
IIRC I'd say they should have both classes (the `transitioned-in` is for animations). If you push whatever you have in a branch and can take a look at it.

**Comment by Pasikonik** [comment]
take a look
https://github.com/cibernox/ember-power-select/pull/443

**Pull request merged**
