### PR TITLE
placeholder when search disabled and no items

### PR DESCRIPTION
**Pull request by patricklx**
fixes issue #589

### CODE REVIEW

**Comment by cibernox** [comment]
Hey, I'm back from holidays. This looks good actually. Can you rebase it so I can give it a try locally?

**Comment by patricklx** [comment]
done

**Comment by cibernox** [comment]
I've just tried it and it looks perfect!
screen shot 0028-08-18 at 09 45 48

Merging

**Comment by cibernox** [comment]
Thank you for this!

**Pull request merged**
