### PR TITLE
use components. Fixes #24

### LINKED ISSUE #24: Refactor partials into components
Use `{{component` helper to render user custom templates.

### PR DESCRIPTION
**Pull request by miguelcobain**

### CODE REVIEW

**Comment by cibernox** [comment]
@miguelcobain The fact that you haven't touched any test and the build is green concerns me. Can you add a test for this use case?

**Comment by miguelcobain** [comment]
@cibernox Agreed.

Question: How can I create a component in a test to be able to reference it by name?

**Comment by cibernox** [comment]
This are component integration tests. I'd say that you don't need to do anything other than creating the component somewhere inside the dummy app.

**Comment by miguelcobain** [comment]
I added the test in a new module for future component customization testing.

**Comment by cibernox** [comment]
Can you rebase? My refactor of yesterday splitting the component into was rather aggresive :grimacing:

**Comment by miguelcobain** [comment]
Squashed commits and rebased.

**Comment by cibernox** [comment]
woot!

**Pull request merged**
