### PR TITLE
Fix issue with this.element being null touchMoveHandler

### PR DESCRIPTION
**Pull request by jdurand**
Seen numerous times in production logs:
Chrome: `Cannot read property 'removeEventListener' of null`
Safari: `null is not an object (evaluating 'e.element.removeEventListener')`

Likely caused by some race condition when the dropdown is destroyed just before some callbacks are fired.

### CODE REVIEW

**Comment by cibernox** [comment]
I'm in the middle of a moving so I'll have 0 time until next week. Please ping me again if I haven't responded by next Wednesday.

**Comment by jdurand** [comment]
👍, FYI I'm running this in production from this same branch

**Comment by jdurand** [comment]
ping!

**Comment by cibernox** [comment]
Thanks for this also!

**Comment by jdurand** [comment]
Hey, thanks for your work; we don't say that often enough!

**Pull request merged**
