### PR TITLE
Fix alignment of selected items in power-select-multiple for RTL layout

### PR DESCRIPTION
**Pull request by behnoodk**
added css classes for `ember-power-select-multiple-option` and `ember-power-select-trigger-multiple-input` in RTL layout to align them to the right, as discussed in #331

### CODE REVIEW

**Comment by cibernox** [comment]
I trust you, but could you explain how `float: initial;` fixes this? I'd expect you use `float: right;` when the component is in rtl mode, and I fail to see how this works.

**Comment by behnoodk** [comment]
Since this is only applied to power-select components with `[dir=rtl]`, `float: initial;` is in fact the same as `float:right;`. I set it to `float:initial;` because there was no reason to set it to `float:right;` explicitly.

The reason we need these two classes in the first place, is that the `float `property of `.ember-power-select-multiple-option` and `.ember-power-select-trigger-multiple-input` is set to `float:left;` . Had they been set to `float:initial;` it would have worked for both `dir=rtl` and default (`dir=ltr`).

Adding these two classes seemed a simple solution, one which I could easily test and there is no risk of breaking anything else.

**Comment by cibernox** [comment]
I just created this quick jsbin (http://jsbin.com/toguji/edit?html,css,output) to learn about that property when float, and I think that `float: initial` is like telling `float: none;`. Try it.

So apparently it's not equivalent to float right.

The reason why I made this to float instead of just be inline-block items is because I don't want that significant whitespace in the templates affects the the separation between items.

**Comment by behnoodk** [comment]
You are right! I changed `float:initial;` to `float:right;` , so they always float, and to make sure whitespace in the templates won't affect the the separation between items.

**Comment by cibernox** [comment]
Thanks!

**Comment by behnoodk** [comment]
Thank you! for your great work on this addon.

**Pull request merged**
