### PR TITLE
Add null check for optionElement in scrollTo

### PR DESCRIPTION
**Pull request by ilucin**
When deleting an entry in multiple select field (with backspace) - scrollTo method can break when accessing offsetTop on optionElement which is null -> [bug reproducing video](https://monosnap.com/file/zjSVlECBVcwMi1BdCus0t7bpRXviXd)

This PR fixes my issue.

### CODE REVIEW

**Comment by cibernox** [comment]
Can you check if if with 1.0.0-alpha.0 you can still reproduce this bug? The entire componen went through a total refactor, and after any refactor, old bugs might have gone and new bugs might have appeared.

**Comment by ilucin** [comment]
Of course, I'll try it out with v1 alpha and let you know

**Comment by ilucin** [comment]
Yep, this null issue is still here - testing with 1.0.0-alpha.10

**Comment by cibernox** [comment]
I believe that this bug has been fixed now

**Comment by ilucin** [comment]
@cibernox nop, it's still here, in the newest version

**Comment by cibernox** [comment]
I have time to track it now. Working on it...

**Comment by cibernox** [comment]
I tried to reproduce it but I couldn't. Any concrete step to get the error?

**Comment by ayuk23** [comment]
It's difficult for me to recreate, but I've definitely had this issue come up numerous times.

**Comment by cibernox** [comment]
Closing this very old PR.

**Pull request closed without merging**
