### PR TITLE
DOCS - Integration Tests

### PR DESCRIPTION
**Pull request by snewcomer**
Issue: https://github.com/cibernox/ember-power-select/issues/391

### CODE REVIEW

**Comment by cibernox** [comment]
Thanks! I'll deploy in a moment

**Comment by et** [comment]
Any chance we could get more available for integration tests? In particular `selectChoose` from the acceptance tests would help a lot.

**Comment by et** [comment]
For context, this would help me when using something like `onchange=(action "someAction")` where `someAction` is doing extra stuff. I need a way to trigger that action to occur.

**Comment by snewcomer** [comment]
@et 
There is a helper:
```
import { typeInSearch, clickTrigger, nativeMouseUp } from '../../../helpers/ember-power-select';
clickTrigger();
nativeMouseUp('.ember-power-select-option:eq(3)');
```
I do something like this as well w/ jquery.

`$(".ember-power-select-option:contains('selectMe')").mouseup()`

**Comment by snewcomer** [comment]
Let me know if this isn't exactly what you needed.  Based on your comment, it seems like this `nativeMouseUp` could go in the docs as well.

**Comment by et** [comment]
Thanks @snewcomer - are you copying/pasting the contents of that helper into your project or is there a way to make this perform a lookup?

**Comment by snewcomer** [comment]
@et either into your own helper file and copy and paste the functions from here.
https://github.com/cibernox/ember-power-select/blob/master/test-support/helpers/ember-power-select.js#L30
or import it
import { typeInSearch, clickTrigger, nativeMouseUp } from '../../../helpers/ember-power-select';

**Comment by et** [comment]
Great! I think it would make sense to explicitly say that on [this page](http://www.ember-power-select.com/docs/test-helpers). Thoughts?

**Comment by snewcomer** [comment]
About the import it does.  Just not about the nativemouseup function.

**Comment by et** [comment]
Sorry, I was unclear. I'm referring to the fact that you need to copy/paste the functions. As someone who is new to the project, it was not obvious where these functions are derived from and that you actually needed to copy them over.

**Comment by snewcomer** [comment]
Sry a little confused, but that might be because I just woke up :) .  Under the integration tests section, it says these helpers must be imported.  In acceptance tests, the whole app is booted up, so you get these functions for free.  Copying and pasting them over if you so decide ensures that any api changes to the helpers in the future doesn't all of a sudden break your build.  Just imagine if you had a project with thousands of tests that only built when your tests pass and there was an api change to the helper.  It may break your build if you aren't careful.  Most people can just import the helpers from power select as long as the project follows the upgrade path as Ember upgrades.

**Comment by et** [comment]
It might be useful then for the install process to copy these test helpers into your project. As I understand it, that's pretty common for addons.

**Comment by cibernox** [comment]
@et I'm also confused. Why would you want to copy the helpers into your app if you can import them?

**Comment by et** [comment]
TIL - ember addons can implicitly drop themselves into your tests helper directory. Sorry about this, I wasn't aware this was a thing. This all makes sense.

**Pull request merged**
