### PR TITLE
[WIP] Support less

### PR DESCRIPTION
**Pull request by simonihmig**
So here comes the PR for #57. This should address the things mentioned in the last comment. 

I added `ember-basic-dropdown.less` here for now to make it work. Will remove once that has been integrated into `ember-basic-dropdown` itself. So don't merge yet!

Apart from that it should be complete. Added a smarter default blueprint, that also addresses #58, and added tests for it.

Hope that looks fine to you. Will then add another PR to `ember-basic-dropdown` to also add Less support there...

### CODE REVIEW

**Comment by simonihmig** [comment]
Waiting for https://github.com/cibernox/ember-basic-dropdown/pull/214 getting merged and released, before being able to proceed here...

**Comment by cibernox** [comment]
EBD merged and released. I've updated the version of EBD in this repo. You can proceed, sir 🎩

**Comment by simonihmig** [comment]
Thanks. Removed the temporary ember-basic-dropdown.less and rebased. Should be ready to go now! 😎

**Comment by simonihmig** [comment]
Just noticed some warning in the Travis log, but apparently they were there also before: https://travis-ci.org/cibernox/ember-power-select/jobs/193561756#L1582
Fyi, in case you did not notice...

**Comment by cibernox** [comment]
Yes, I think it has to do with mirage. Perhaps I should update it. Either way, thank you so much for this. This also closes #58 !

**Comment by cibernox** [comment]
Published in 1.3.0. I'll update the docs now.

**Comment by simonihmig** [comment]
No Problem, was fun! Thanks for the quick response and release!

You can close #57 as well, btw.

**Pull request merged**
