### PR TITLE
don't use ember-truth-helpers in addon directly

### LINKED ISSUE #810: remove ember-truth-helpers from dependencies
is it really necessary to bring them in as a dependency? Would you consider moving them to devDependencies for the dummy app, and I could submit a PR that replaces all usage of truth helpers in the addon with computed properties?

### PR DESCRIPTION
**Pull request by akatov**
fixes #810

### CODE REVIEW

**Comment by akatov** [comment]
@cibernox what do you think?

**Comment by cibernox** [comment]
I thought that it was a WIP. Those examples look good, but there is still some usages. The tricky ones. Example: https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select/options.hbs#L24

**Comment by akatov** [comment]
thanks! I totally missed that one. Will send you an update shortly

**Comment by akatov** [comment]
It's a bit more complex to use computed properties, since some other parts of the `publicAPI` get affected by the change of what is passed to the options component. In particular the highlighted property.
I'd be happy to look into doing this properly in a separate PR, but for now I just wanted to finish off this one...

**Comment by cibernox** [comment]
Yeah, that is what I though. I'm unsure if I should merge this, because if it doesn't fully achieve the final goal (remove a runtime dependency) there is no benefits and a certain (albeit small) amount of churn for people who had created their own components and copy/pasted the original templates.

Let's think on a plan to remove it entirely.

**Comment by akatov** [comment]
well, with the final commit the goal of removing the runtime dependency is achieved (by replacing the eq helper with a custom helper). Moreover, this should still work with the old templates, since the data didn't change.
Then again I'm not sure whether this would warrant a breaking change nevertheless because if someone was using e-p-s and was using truth helpers without explicitly specifying them as a dependency, they would have to now require them explicitly.
In the end, this PR probably doesn't provide enough benefit overall, especially because it makes things more complex in the templates, which as you said are part of the public API, so maybe it is better to hold off until we change the actual data and can remove all the custom template helpers (which would certainly warrant a major version bump).

**Comment by cibernox** [comment]
After some thought I decided to continue using the helpers. It is the 6th most used addon in the ecosystem (it will be present it most apps anyway) and it's height footprint is so small that I think it's not worth it.

If I remove a runtime dependency, it would be ember-concurrency as it's not so small.

**Pull request closed without merging**
