### PR TITLE
Update to ember 4.8 & packages

### LINKED ISSUE #1569: Update app to ember 4.8.x & packages
Now we can also update this repo to `ember 4.8.x` like we have already done for `ember-basic-dropdown`

### PR DESCRIPTION
**Pull request by mkszepp**
fix #1569 & #1563

### CODE REVIEW

**Comment by mkszepp** [comment]
@cibernox updated more/less everything, now the app works on ember 4.
I have fixed also some examples, because they were not correct / buggy after making as component

**Comment by mkszepp** [comment]
the tests for embroider are failing because ember data was buggy from 4.8.x to 4.11.0. starting with 4.11.1 the test should not anymore fail.

**Comment by cibernox** [comment]
Fix it as part of this PR on another one?

**Comment by mkszepp** [comment]
i do it in this PR, just wait a secound :D

**Comment by mkszepp** [comment]
@cibernox can you approval the workflow, than we see if we are ready

**Comment by cibernox** [comment]
🤞

**Comment by mkszepp** [comment]
interresting that this tests was never failed before... we need to fix it like in this PR: https://github.com/cibernox/ember-power-select/pull/1532

**Comment by cibernox** [comment]
FWIW, I think I'm going to merge this as is and we can fix the embroider optimized scenario later.

**Pull request merged**
