### PR TITLE
add test for multiple component

### PR DESCRIPTION
**Pull request by Pasikonik**
in progress

### CODE REVIEW

**Comment by cibernox** [comment]
Just to let you know, you might have just discovered a bug :rocket:

**Comment by cibernox** [comment]
I did some heavy refactoring in Ember Basic Dropdown, which simplified it significantly, and it might have fixed the bug that prevented your test from working. 

Can you rebase and try again?

**Comment by Pasikonik** [comment]
Actually It works now.

**Comment by cibernox** [comment]
@Pasikonik I imagined it. This test failing lead me to pull the string a discover some subtle misbehaviour.

I was quite a yak shaving BTW (https://github.com/cibernox/ember-basic-dropdown/compare/3b2697ea48aee73ddd6fa5c5529885bcd235b96f...master) but I think that also responsibilities are better divided now.

**Comment by cibernox** [comment]
Thanks for the effort!

**Pull request merged**
