### PR TITLE
Allow to highlight an object option without use the same reference

### PR DESCRIPTION
**Pull request by rogeraraujo90**
Fixes: https://github.com/cibernox/ember-power-select/issues/1629

### CODE REVIEW

**Comment by mkszepp** [comment]
Thank you!

**Comment by rogeraraujo90** [comment]
> Thank you!

Hi! Can we have a beta tag with this commit? In addition, can you anticipate to me how the styles should be imported in v8? Thanks!

**Comment by mkszepp** [comment]
@rogeraraujo90 yes release everything today in the next beta.

For importing styles in v8 see Documentation -> Installation -> Manual installation https://ember-power-select.com/docs/installation

If something is unclear let me know. In V8 you need also to add `<BasicDropdownWormhole />` in `application.hbs` (everything is listed in docs).

**Comment by mkszepp** [comment]
@rogeraraujo90 released in `8.0.0-beta.5`

**Comment by rogeraraujo90** [comment]
> @rogeraraujo90 released in `8.0.0-beta.5`

Thanks a lot! 🙂

**Comment by rogeraraujo90** [comment]
> @rogeraraujo90 yes i will release everything today in the next beta.
> 
> For importing styles in v8 see Documentation -> Installation -> Manual installation https://ember-power-select.com/docs/installation
> 
> If something is unclear let me know. In V8 you need also to add `<BasicDropdownWormhole />` in `application.hbs` (everything is listed in docs).

My project uses `ember-cli-sass`. Add `@import 'ember-power-dropdown';` in `app.scss` breaks the App on v8 (it was working on v7). But looks like the styles are working without the import so all good. The cons is that I cannot reuse exported variables from styles now.

**Comment by mkszepp** [comment]
@rogeraraujo90 ups its a docs bug... 'ember-basic-dropdown' is correct... i will fix it... thank for reporting

**Pull request merged**
