### PR TITLE
Apply toPlainArray on @selected for publicAPI

### PR DESCRIPTION
**Pull request by tobiaszwalczak**
Fix for: https://github.com/cibernox/ember-power-select/issues/1341

### CODE REVIEW

**Comment by cibernox** [comment]
@tobiaszwalczak good catch. However I don't get why this change would require to change an existing test, why is that?

**Comment by tobiaszwalczak** [comment]
@cibernox Ah right, that goes maybe a bit far for this PR. As I fixed the `@selected` attribute to resolve an issue (https://github.com/cibernox/ember-power-select/issues/1341) with the `ember-power-select-is-selected` helper and the `aria-selected` attribute it influences, I wanted the test to reflect that the `aria-selected` attribute works properly. The test should still reflect the previous functionality it tested.

But I'm happy to revert the test file if you want me to 😄

**Comment by cibernox** [comment]
I believe I've just fixed this in master.

**Comment by cibernox** [comment]
I just released 4.0.0 final including this change, can you give it a go?

**Comment by tobiaszwalczak** [comment]
@cibernox Just tried out `4.0.0`and works like a charm now, thanks! 👌 Going to close the PR and the related Issue.

**Pull request closed without merging**
