### PR TITLE
increase z index of dropdown content

### PR DESCRIPTION
**Pull request by willrax**
as discussed in slack, this seems like it could be a sane default.

### CODE REVIEW

**Comment by cibernox** [comment]
Woot!

I'll cut a new release over the weekend.

**Comment by willrax** [comment]
Thanks! :tada:

**Comment by miguelcobain** [comment]
Well, bootstrap modals have a default of z-index 1050: https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L283

:stuck_out_tongue_winking_eye:

**Comment by cibernox** [comment]
@miguelcobain I wonder why that specific number. Seems too specific to be arbitrary.

**Comment by cibernox** [comment]
Also seems that dropdowns have 1000.

**Comment by willrax** [comment]
i just checked our css and our side panel is something like 900 :/

**Comment by miguelcobain** [comment]
I think it really is arbitrary. AFAIK z-index values aren't relevant, just how they relatively compare to each other.

Perhaps they needed to stack other elements of the framework in depth. Modals, being the topmost of them (I think) ended up with that value. Don't really know.

**Comment by jamesdixon** [comment]
Definitely arbitrary. I just ran into the same issue using [liquid-tether](https://github.com/pzuraq/liquid-tether) for modals and they too use 1050 for their z-index. Think it might be worth bumping up the default a bit more? Maybe to 1,475,348? :+1:

**Pull request merged**
