### PR TITLE
Add full embroider compatibility

### PR DESCRIPTION
**Pull request by mydea**
This PR hopefully makes this addon fully embroider compatible.

Note that this relies on https://github.com/embroider-build/embroider/pull/922 (or something along these lines) to be merged - see https://github.com/embroider-build/embroider/issues/921 (in order for embroider compatibility to really work).

This is based on https://github.com/cibernox/ember-power-select/pull/1419 in many ways, but there have been a bunch of changes in the meanwhile, so it was somewhat easier to reproduce the changes than to deal with merge conflicts etc.

I also added some tests to ensure we keep supporting overwriting the default components (which would break with certain implementations, e.g. if we imported the default components in JS-land).

### CODE REVIEW

**Comment by roomman** [comment]
Would love to see this progress. 👍🏻

I was using [this Webpack workaround](https://gist.github.com/bendemboski/907b8a53040213a911301ad48172b99b) but one of our projects uses `power-select-multiple` and that relies on dynamically setting `@triggerComponent`. 🤦🏻‍♂️

**Comment by mydea** [comment]
I rebased this on current master and resolved any new conflicts, should be "good" again!

**Comment by cibernox** [comment]
I managed to make CI a week ago, so if CI fails now I believe this time should be legitimate failures.

**Comment by mydea** [comment]
OK, I think the failing tests should be fixed now :crossed_fingers:

**Comment by cibernox** [comment]
@mydea I see, so in embroider-land one can't pass a component name to the select and have the select call `{{component @compName}}` on it. It has to be passed in as a component from the outside from the beginning.

I assume that this is not a breaking change as it's a requirement for embroider.

CI is green now! Merging it

**Comment by cibernox** [comment]
I noticed that CI is not running embroider scenarios. I had to comment them because CI wouldn't pass. Can you add them back to `ember-try.js` and `.github/workflows/ci.yml`?

**Comment by mydea** [comment]
> @mydea I see, so in embroider-land one can't pass a component name to the select and have the select call `{{component @compName}}` on it. It has to be passed in as a component from the outside from the beginning.
> 
> I assume that this is not a breaking change as it's a requirement for embroider.
> 
> CI is green now! Merging it

Yes, when passing something through like this you need to use `{{component (ensure-safe-component @arg)}}`, and it should be used by the user as `@arg={{component 'my-component'}}` instead of `@arg='my-component'`. The latter will still work in non-embroider land, so it should not be breaking (and I actually added a bunch of tests covering both scenarios). I'll need to see how I can make some of the tests optional in embroider, but that should be doable!

**Comment by cibernox** [comment]
Great! Merged!

**Pull request merged**
