### PR TITLE
Fix iOS issue with touchend event

### PR DESCRIPTION
**Pull request by jdurand**
Fixes https://github.com/cibernox/ember-power-select/issues/919

### CODE REVIEW

**Comment by cibernox** [comment]
@jdurand What I don't get is how this works in the other browsers. Chrome by example also has a native "closest" function.

**Comment by luketheobscure** [comment]
Might be safer to program defensively since based on the discussion here it seems like `closest` will sometimes be returning an array, and sometimes an element. Maybe check if `optionItem` is an array before trying to access anything on it?

**Comment by jdurand** [comment]
My assumption that `closest` was broken was wrong.
The issue is that `e.target.closest('[data-option-index]')` doesn't return an array; it returns an element. the `touchend` handler was expecting an array as is the case with `$(e.target).closest('[data-option-index]')`

**Comment by cibernox** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/Element/closest , `closest` always return an element, never an array. Which also makes sense to me, the `closest` element can only be one.

This change seems correct, what I'm not very sure is why chrome for android doesn't exercises this. I'll merge once CI pases.

**Comment by jdurand** [comment]
@cibernox my guess is that this case is handled by the click handler on Android, otherwise it would fail the same way. Perhaps somebody with an Android phone could confirm this.

**Comment by cibernox** [comment]
I have one. Can you point me to an failing example?

**Comment by jdurand** [comment]
The language select here reproduces the issue on iOS: http://widgets.dev.libroreserve.com/booking/DEMO/DEMO/

**Comment by cibernox** [comment]
@jdurand Minified it's almost impossible to replicate. But I'll merge it. It makes total sense.

**Comment by cibernox** [comment]
@jdurand Released in 1.8.5.
@luketheobscure This also includes your latest PR 🙇

**Pull request merged**
