### PR TITLE
add lato font

### PR DESCRIPTION
**Pull request by miguelcobain**
I was seeing an ugly arial font, until I found out why.

### CODE REVIEW

**Comment by cibernox** [comment]
Let's look at it

**Comment by miguelcobain** [comment]
The styles define "Lato" as the font family. However, if your pc doesn't have that font, displays Helvetica Neue, Helvetica or Arial.
Linux folks see Arial because Helvetica is proprietary.

**Comment by cibernox** [comment]
I' so used to Helvetica that I thought that it was publicly available :open_mouth:

**Comment by samselikoff** [comment]
yep source is here: https://github.com/samselikoff/ember-cli-mirage/tree/gh-pages

**Pull request merged**
