### PR TITLE
Using the seach action updates the seachbox

### PR DESCRIPTION
**Pull request by cibernox**

### CODE REVIEW

**Comment by miguelcobain** [comment]
Double typo? :P

**Comment by cibernox** [comment]
What?

**Comment by miguelcobain** [comment]
Using the **seach** action updates the **seachbox**. 

I couldn't care less. Just being annoying. :P

**Comment by cibernox** [comment]
Let me tell you that you excel at that, Sir.

**Comment by miguelcobain** [comment]
Sorry. :pray:

**Pull request merged**
