### PR TITLE
Expose power-select component as 'ember' seems redundant

### PR DESCRIPTION
**Pull request by achambers**

### CODE REVIEW

**Comment by cibernox** [comment]
Actually makes a lot of sense. The only but is that you need to di a find and replace of `{{#ember-power-select}}` in the docs too.

**Comment by cibernox** [comment]
And probably also deprecate the old name but keep it working for a while.

**Comment by achambers** [comment]
Okie doke...Will do.  Any thoughts on how to deprecate something like that?

I'll do it for both repos.

**Comment by cibernox** [comment]
```
import EmberPowerSelectComponent from 'ember-power-select/components/ember-power-select';
export default EmberPowerSelectComponent.extend({
  init() {
    this._super(...arguments);
    Ember.deprecate('Use new name');
  }
});
```

Something like that?

**Comment by achambers** [comment]
Sweet

**Comment by achambers** [comment]
@cibernox Any thoughts on what should go in the `options` hash for this stuff?

http://emberjs.com/deprecations/v2.x/#toc_ember-debug-function-options

**Comment by cibernox** [comment]
It's optional, correct? If it's not put that it will removed in 0.4 and create a any id that makes sense. If it gives you troubles use `console.warn` and continue with your life, it's not a big deal.

**Comment by cibernox** [comment]
I've applied the same change to ember-basic-dropdown. 

If "something happens" (:wink:) let me know and I continue from here.

**Comment by cibernox** [comment]
I supossed that you are very busy, so I did it yesterday.

Closed vía #88

**Comment by achambers** [comment]
I figured that might be the case. Sorry mate....Have been under the pump.
Cheers ;)

**Pull request closed without merging**
