### PR TITLE
Replace Ember.A with a manual check for fastboot compat

### PR DESCRIPTION
**Pull request by igorT**
Ember.A doesn't work yet due to https://github.com/ember-fastboot/ember-cli-fastboot/issues/251

### CODE REVIEW

**Comment by igorT** [comment]
@cibernox did

**Comment by igorT** [comment]
Beta fails, but seems like it fails on master as well

**Comment by cibernox** [comment]
Yes, it's broken on glimmer2 . That's what I'm checking right now.

**Comment by cibernox** [comment]
Thanks!

**Pull request merged**
