### PR TITLE
Only load polyfill when not in FastBoot environment

### LINKED ISSUE #1154: Options component broken in fastboot
https://github.com/cibernox/ember-power-select/blob/7ffe3f0a3d2fdc7132b3bf991245d93610f0ef7c/addon/components/power-select/options.js#L6-L23

The above polyfill results in an infinite rendering invalidation in a fastboot environment.

The basic error:
`TypeError: Cannot read property 'prototype' of undefined`

I think we could just wrap it in a:
```
if(typeof FastBoot === undefined){
    ... polyfill ...
}
```

### PR DESCRIPTION
**Pull request by nickschot**
fixes #1154

### CODE REVIEW

**Comment by cibernox** [comment]
Makes a lot of sense!

**Comment by cibernox** [comment]
Published a new patch version for this. Great catch!

**Comment by nickschot** [comment]
I probably ran into it because I use an extended options component which I pass into power-select.

**Comment by cibernox** [comment]
That can also cause the component to be eagerly imported and make the polyfill run. Either way, you fixed it :D

**Pull request merged**
