### PR TITLE
Multiselect: for disabled options, hide remove btn

### PR DESCRIPTION
**Pull request by toh995**
This is my first PR here, so please let me know if I'm missing anything!

For multiselects, if an option is disabled, AND that option is selected, then we shouldn't be able to "remove" that option from the selection. See videos below:

### Before
https://user-images.githubusercontent.com/52012721/139349835-7195a4f9-073f-455b-a4b6-068bb99ddb09.mov

### After
https://user-images.githubusercontent.com/52012721/139349765-f1a67204-e341-4b61-9058-96c783ec2569.mov

### CODE REVIEW

**Comment by toh995** [comment]
Hello @cibernox are you the right person to tag to review this one?

**Comment by cibernox** [comment]
I am. Checking it.

**Review by cibernox — APPROVED** [review]

**Comment by cibernox** [comment]
It looks great! It was a clear oversight. Can you please add an entry on the Changelog describing this change? I'll merge it after that.

**Comment by toh995** [comment]
Hi @cibernox thanks for the feedback!
I added a changelog entry - does it look correct?

**Comment by cibernox** [comment]
Yes! Merging!

**Comment by lougreenwood** [comment]
Just ran into this after upgrading to 5.1 - we now have failing tests and need to re-architect some UI. I wonder if this should be a breaking change?

For reference, our use case is a multi-select input where users list people to "invite", if a user adds an invalid email address we show an inline validation message and invite the user to delete the item (and disable the "submit" button until the invalid emails are removed).

With this change we need to not allow adding an invalid email to the multi select and come up with a new interaction which warns the user that the value they entered into the multi-select input is invalid and a new value should be entered...

**Comment by toh995** [comment]
Yeah, seems fair to call this a breaking change 👍

**Comment by cibernox** [comment]
I didn't anticipate this to be breaking, I'll undo it and consider options. 
As a base behavior, if an element is disabled it should not be possible to add or remove it. It's a reasonable default. But perhaps it should be configurable.

**Comment by cibernox** [comment]
I reverted this in 5.0.2. I'll open a PR again with the revert of the rever and iterate there on a solution.

**Comment by toh995** [comment]
Sounds good, thanks @cibernox!

**Comment by lougreenwood** [comment]
Thanks @cibernox & @toh995.

Sorry for undercutting your first PR @toh995 - looking forward to seeing it land again and updating our code to work with it 😊.

**Comment by toh995** [comment]
Hey @lougreenwood just seeing this now - no worries! Thanks for bringing this up

**Pull request merged**
