### PR TITLE
Document using POJOs as selected

### PR DESCRIPTION
**Pull request by orf**
Is this OK?

### CODE REVIEW

**Comment by omairvaiyani** [comment]
@orf Looks like the test failed because 'find-by' was not found as a helper. 

You need to add [ember-composable-helpers](https://github.com/DockYard/ember-composable-helpers) to this repos dependencies. Ideally limiting to the tree to 'find-by' like below.

```javascript
// ember-cli-build.js
var app = new EmberApp(defaults, {
    ...
    'ember-composable-helpers': {
      only: ['find-by']
    }
    ...
  });
```

**Comment by cibernox** [comment]
I think that when this PR was created master was red but now it should pass the tests after a rebase

**Comment by orf** [comment]
Oh dear. I rebased it on master and now it's a tad fucked it seems!

**Comment by orf** [comment]
So it's failing because `unit/utils/group-utils-test.js: should pass ESLint` which I haven't touched. Is it OK to merge anyway?

**Comment by cibernox** [comment]
I don't see that ESlint error that you mention. However I'm going to hold this a bit more until I implement #773, since can change the narrative or add another option to the explanation.

**Comment by cibernox** [comment]
I think I can close this since this part of the docs have already been improved.

**Comment by Caltor** [comment]
@cibernox The docs still don't say how to handle this using a computed property or `find-by`.

**Comment by cibernox** [comment]
@Caltor where would you add an example for that? Maybe the "How to use" section?
If you have time to make a PR improving the docs I think that would be valuable. Often library authors have blindspots because we know the library too well.

**Comment by Caltor** [comment]
@cibernox Yeah I would suggest the "How to use" section. If you're happy for me to mess with the docs I'll give it a go. It will be only my second PR tho so please be gentle with me. ;)

**Comment by cibernox** [comment]
Go ahead! The docs are the dummy app in this very repo. More often that not, people with less knowledge of the library are the one who write the better docs, as they explain things more thoroughly.

**Comment by Caltor** [comment]
@cibernox OK I've created https://github.com/cibernox/ember-power-select/pull/1177. Hopefully I've done it right but please let me know if I've messed up.

**Comment by Caltor** [comment]
@cibernox Looks like the build is failing but it has been failing for the last 28 days so I don't think it is anything I have done. See https://travis-ci.org/cibernox/ember-power-select/builds

**Comment by Caltor** [comment]
@cibernox I've fixed the build issue on a separate PR for you in case you reject the doc changes PR (which also incorporates the fix) so you can take your pick.

**Pull request closed without merging**
