### PR TITLE
Remove project jscs warnings

### PR DESCRIPTION
**Pull request by yethon**
This adds [ember-suave](https://github.com/DockYard/ember-suave) which is based on [jscs](http://jscs.info)

Most of the changes are trivial such as using single quotes vs. double quotes.  However, others enforce ES2015 code style, which helps make it second nature.

When a 'rule' is broken, it will show up as a test failure with a message and line number.

I also found that creating exceptions for rules was a straightforward process.

FYI - These are the rules I made changes for in ember-power-select:

`disallowConstOutsideModuleScope: `const` should only be used in module scope (not inside functions/blocks)`

`requireParenthesesAroundArrowParam: Wrap arrow function expressions in parentheses`

`requireSpaceBeforeBlockStatements: One (or more) spaces required before opening brace for block expressions`

`disallowTrailingComma: Extra comma following the final element of an array or object literal`

`validateQuoteMarks: Invalid quote mark found`

`requireObjectDestructuring: Property assignments should use destructuring`

`requireEnhancedObjectLiterals: Property assignment should use enhanced object literal function`

`requireSpread: Illegal use of apply method. Use the spread operator instead` 

`equireBlocksOnNewline: Missing newline after opening curly brace`

### CODE REVIEW

**Comment by yethon** [comment]
Well, at least we know it works 😄 
I am going to continue chipping away at the remaining rules...

**Comment by yethon** [comment]
Bad News: [https://github.com/ember-cli/ember-cli/issues/5498](https://github.com/ember-cli/ember-cli/issues/5498)

It looks like there may be an issue with running these against the actual add on code, all of my changes were against tests.
I'll investigate further....

**Comment by yethon** [comment]
@miguelcobain 
I noticed your name in this issue [https://github.com/ember-cli/ember-cli/pull/5592](https://github.com/ember-cli/ember-cli/pull/5592) which is related to [https://github.com/ember-cli/ember-cli/issues/5498](https://github.com/ember-cli/ember-cli/issues/5498) and thought I'd reach out for some help... hope you don't mind 😃 

When I submitted this PR, I thought that I had addressed all of the jscs errors.  If I run the tests locally, everything is fine (ignoring [https://github.com/cibernox/ember-power-select/issues/492](https://github.com/cibernox/ember-power-select/issues/492) for the moment). 

However, after submitting the PR, phantom shows that the linting never ran against the actual addon code, only the files in tests.  Running `ember test -f jscs` like you pointed out, shows me all of the additional jscs errors.

Were you able to successfully set up ember-suave in any of your addons?  It looks like it's in some of your package.json files, was there additional modifications required to get it to run across the entire project?

**Comment by miguelcobain** [comment]
The addon was need being linted and it was fixed in ember-cli 2.4.3.

I was able to set up ember-suave in ember-paper. And I see the tests running on travis.

What is the problem here exactly? JSCS tests are running locally but not on travis?

**Comment by yethon** [comment]
After I installed ember-suave, I ran, `ember test --server` and fixed all reported test failures (except the unrelated [https://github.com/cibernox/ember-power-select/issues/492](https://github.com/cibernox/ember-power-select/issues/492))

After I pushed my branch and travis\phantom took over, I saw a whole bunch of new jscs failures in the addon code. It turns out that only the failures in the test files were reported when I was working locally.  The failures in the addon code were only reported in travis.  However, I did see them locally if I did `ember test -f jscs`, like you pointed out.

I'm not sure if I'm looking at some sort of bug, or if there is additional configuration required somewhere to get the linting to happen across the entire project, when running tests locally.  Shouldn't `ember test --server` report all of the jscs errors in the addon?  It's a major nuisance to think you're tests pass, only to have travis tell you otherwise 😃

**Comment by miguelcobain** [comment]
That is strange. travis should report the same thing as locally.

**Comment by yethon** [comment]
*insert eye roll* 
Seems I was wrong.  The tests are now showing the JSCS errors when I run this locally.  I can only speculate as to what was going on when I was running this yesterday.
Sorry to waste your time @miguelcobain 
Proceeding with updates...

**Comment by cibernox** [comment]
Closing for now, let me know if you want to reopen tis

**Pull request closed without merging**
