### PR TITLE
Allow customizing the search message component

### PR DESCRIPTION
**Pull request by rlivsey**
Adds `noMatchesMessageComponent` and `searchMessageComponent` options to customize the no-matches and search message components respectively.

### CODE REVIEW

**Comment by cibernox** [comment]
As discussed in person, I'm in on the `searchMessageComponent` but not so much in the `noMatchesMessageComponent`, because the component accepts an `else` block where you can already render any component you want.

**Comment by rlivsey** [comment]
👍 

I've removed the `noMatchesMessageComponent` and rebased so it just adds the `searchMessageComponent` now.

**Comment by cibernox** [comment]
@rlivsey Tests are failing

**Comment by cibernox** [comment]
Ok, disregard the failure. The components seems to be entirely broken in beta, no idea why. Merging.

**Pull request merged**
