### PR TITLE
fixed search not focusing

### PR DESCRIPTION
**Pull request by robclancy**
fixes https://github.com/cibernox/ember-power-select/issues/1141

Not sure the real issue but we need this to work, it's terrible UX without it.

### CODE REVIEW

**Comment by knownasilya** [comment]
Would love to see this merged. @robclancy looks like you need to rebase before it can be merged.

**Comment by cibernox** [comment]
If this is rebased I think we can safely merge it.

**Comment by robclancy** [comment]
Isn't it fixed with https://github.com/cibernox/ember-power-select/commit/6bc13ba270bf49ec3d386ee2666d445d0afa946b?

**Comment by cibernox** [comment]
@robclancy I believe it should. Can you virify?

**Pull request closed without merging**
