### PR TITLE
feat: allow to customize PowerSelectMultiple placeholder by `@placeholderComponent`

### PR DESCRIPTION
**Pull request by wozny1989**
# Problem:
Passing path to custom placeholder component in `PowerSelectMultiple` on `@placeholderComponent` attribute don't make any change.

# Task:
 - [x] Move `<input />` search multiple select to separate component
 - [x] Allow to display custom placeholder as it works in `<PowerSelect />`:
    ```hbs
    <PowerSelectMultiple
      @options={{this.countries}}
      @placeholder="test"
      @placeholderComponent={{component "custom-placeholder"}}
      @onChange={{set this "foo")}} 
      as |country|
    >
      {{country.name}}
    </PowerSelectMultiple>
    ```
 - [x] Allow to display custom placeholder for `<PowerSelectMultiple />` with `@searchEnabled` attribute on `true`:
    ```hbs
    <PowerSelectMultiple
      @searchEnabled={{true}}
      @options={{this.countries}}
      @placeholder="test"
      @placeholderComponent={{component "custom-placeholder-multiple"}}
      @onChange={{set this "foo")}} 
      as |country|
    >
      {{country.name}}
    </PowerSelectMultiple>
    ```
    On this case we have an access to additional properties: `@displayPlaceholder` and `inputComponent`. 
    It's more powerful because now we have control where we want to display **input search** element:
   ```hbs
    {{!-- custom-placeholder-multiple.hbs --}}
    {{#if @displayPlaceholder}}
      <div class="text-warning">
        {{@placeholder}}
      </div>
    {{/if}}

    <@inputComponent class={{if @displayPlaceholder "position-absolute top-0"}} />
   ```   

    https://user-images.githubusercontent.com/36460224/215347545-c2eb1378-6bb6-483e-8437-3a893decea4c.mp4

### CODE REVIEW

**Comment by wozny1989** [comment]
@cibernox It's more like a feature, not fix because it provides additional things that where not available around `placeholderComponent` in `<PowerSelectMultiple />` and `<PowerSelectMultiple @searchEnabled={{true}} />`

Just let me know if I can do something more 🙏

**Review by cibernox — APPROVED** [review]

**Comment by cibernox** [comment]
I missed this for months, but I don't oppose to this idea. At first I thought that replacing the entire trigger component was enough, but I can see how replacing the entire trigger just because the thing you want to change is the placeholder can be cumbersome. 

Can you check if the failing test is related to this PR or just happens to be failing in master? I'll merge it after

**Comment by cibernox** [comment]
Thanks! I’m AFK, but I will cut a new release tonight

**Comment by wozny1989** [comment]
Update `package-json.lock` solved a problem with `Tests` pipe on CI. 

Also I had to change path in `package.json` for `ember-code-snippet` package to avoid using `ssh` in `package-json.lock` - it was another problem with `Tests` pipe.

Thanks for merge! 🙏

**Pull request merged**
